[package]
name = "locat"
version = "0.2.0"
edition = "2021"
# only publish to private registry
publish = ["itsrainingmani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
